site_name: Resources for New Astronomy Research Students
nav:
    - Home: index.md
    - Astronomy Tools: tools.md
    - Software Practices: software.md 
    - Publishing in Astronomy: publishing.md
    - Writing Papers: writing.md
    - Recommended Reading: reading.md
    - Values: values.md
    - Laplace Approximation: laplace.md

theme:
  name: "material"
  icon:
    logo: material/telescope 

repo_url: https://github.com/benjaminpope/startup
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:  # Render LaTeX via MathJax
      generic: true
  - pymdownx.snippets:  # Include one Markdown file into another
      base_path: docs
  - admonition
  - toc:
      permalink: "¤"  # Adds a clickable permalink to each section heading
      toc_depth: 4
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list # Allows images
  - md_in_html # Allows images
  - footnotes

extra_javascript: # Used for MathJax
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
